version: '3.2'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
      # MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      # MONGO_INITDB_DATABASE: ${DB_NAME}

#  rabbitmq:
#    image: "rabbitmq:3.8-management-alpine"
#    container_name: nodejs-rabbitmq-rabbitmq
#    hostname: rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    volumes:
#      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=admin